version: '3'
services:
  postgresql-b:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    volumes:
      - ./data/db1:/var/lib/postgresql/data
    ports:
      - 5432:5432

  postgresql-b1:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    volumes:
      - ./data/db2:/var/lib/postgresql/data
    ports:
      - 5433:5432

  postgresql-b2:
    image: postgres
    restart: always
    environment:
      PPOSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    volumes:
      - ./data/db3:/var/lib/postgresql/data
    ports:
      - 5434:5432